spring:
  application:
    name: order-app
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8060


server:
  port: 9081
security:
  oauth2:
    client:
      client-id: order-app
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.immoc.com:9090/oauth/token_key


