server:
  port: 7070

spring:
  application:
    name: gateway-app


zuul:
  sensitive-headers:
  routes:
    token:
      url: http://127.0.0.1:9090
    order:
      url: http://127.0.0.1:9081
    user:
      url: http://127.0.0.1:9081



security:
  oauth2:
    client:
      client-id: gateway
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.immoc.com:9090/oauth/token_key
